title: "J. Feavel"
url: "https://jfeavel.dev"
baseurl: ""
collections:
  exemplars:
    output: true
  side_projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
